// <auto-generated />
using System;
using CompraProg.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProg_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303174232_AddCotacoes")]
    partial class AddCotacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CompraProg.Infrastructure.Persistence.Entities.CestaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.ToTable("Cestas");
                });

            modelBuilder.Entity("CompraProg.Infrastructure.Persistence.Entities.ClienteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CompraProg.Infrastructure.Persistence.Entities.CotacaoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CodBdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TpMerc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "DataPregao")
                        .IsUnique();

                    b.ToTable("Cotacoes");
                });

            modelBuilder.Entity("CompraProg.Infrastructure.Persistence.Entities.ItemCestaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("ItensCesta");
                });

            modelBuilder.Entity("CompraProg.Infrastructure.Persistence.Entities.ItemCestaEntity", b =>
                {
                    b.HasOne("CompraProg.Infrastructure.Persistence.Entities.CestaEntity", "Cesta")
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("CompraProg.Infrastructure.Persistence.Entities.CestaEntity", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
